config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newapp.urls", namespace="newapp")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newapp/urls.py
from django.urls import path

from newapp.apps import NewappConfig
from newapp.views import (BlockMailingView, HomeView, MailingAttemptListView,
                          MailingClearAttemptsView, MailingRecipientCreateView,
                          MailingRecipientDeleteView, MailingRecipientListView,
                          MailingRecipientUpdateView, MailingRecipientView,
                          MessageCreateView, MessageDeleteView,
                          MessageListView, MessageUpdateView, MessageView,
                          NewsletterCreateView, NewsletterDeleteView,
                          NewsletterListView, NewsletterUpdateView,
                          NewsletterView, SendNewsletterView,
                          UserMailingStatisticsView)

app_name = NewappConfig.name

urlpatterns = [
    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message_detail/<int:pk>/", MessageView.as_view(), name="message_detail"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path(
        "mailingrecipient_detail/<int:pk>/",
        MailingRecipientView.as_view(),
        name="MailingRecipient_detail",
    ),
    path(
        "mailing_list/",
        MailingRecipientListView.as_view(),
        name="mailingrecipient_list",
    ),
    path(
        "mailing_create/",
        MailingRecipientCreateView.as_view(),
        name="MailingRecipient_create",
    ),
    path(
        "home/<int:pk>/update/",
        MailingRecipientUpdateView.as_view(),
        name="MailingRecipient_update",
    ),
    path(
        "home/<int:pk>/delete/",
        MailingRecipientDeleteView.as_view(),
        name="MailingRecipient_delete",
    ),
    path("newsletter_list/", NewsletterListView.as_view(), name="newsletter_list"),
    path(
        "newsletter_detail/<int:pk>/",
        NewsletterView.as_view(),
        name="newsletter_detail",
    ),
    path("newsletter_create", NewsletterCreateView.as_view(), name="newsletter_create"),
    path(
        "newsletter_update/<int:pk>/",
        NewsletterUpdateView.as_view(),
        name="newsletter_update",
    ),
    path(
        "newsletter_delete/<int:pk>/",
        NewsletterDeleteView.as_view(),
        name="newsletter_delete",
    ),
    path("home/", HomeView.as_view(), name="home"),
    path(
        "message_attempt_list/",
        MailingAttemptListView.as_view(),
        name="message_attempt_list",
    ),
    path(
        "send_newsletter/<int:pk>/",
        SendNewsletterView.as_view(),
        name="send_newsletter",
    ),
    path(
        "newsletter_block/<int:mailing_id>/block/",
        BlockMailingView.as_view(),
        name="newsletter_block",
    ),
    path(
        "user/statistics/", UserMailingStatisticsView.as_view(), name="user_statistics"
    ),
    path(
        "clear-mailing-attempts/",
        MailingClearAttemptsView.as_view(),
        name="clear_mailing_attempts",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (BlockUserView, ChangePasswordView, PasswordResetView,
                    RegisterView, UserDetailView, UserListView,
                    email_verification)

app_name = "users"


urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="newapp:home"), name="logout"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_block/<int:user_id>", BlockUserView.as_view(), name="user_block"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("profile/<int:pk>", UserDetailView.as_view(), name="user_profile"),
]

newapp/models.py
import logging

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from users.models import CustomsUser

logger = logging.getLogger(__name__)


class MailingRecipient(models.Model):
    """Модель «Получатель рассылки»:"""

    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=150, verbose_name="Ф.И.О")
    comment = models.TextField()
    owner = models.ForeignKey(
        CustomsUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = ["full_name", "email"]
        permissions = [
            ("can_view_all_mailingrecipient", "can view all mailingrecipient"),
        ]


class Message(models.Model):
    """Модель «Сообщение»:"""

    subject = models.CharField(max_length=250, verbose_name="тема письма")
    body_of_the_letter = models.TextField(verbose_name="Сообщение")
    owner = models.ForeignKey(
        CustomsUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщений"
        ordering = ["subject"]
        permissions = [
            ("can_view_all_messages", "can view all messages"),
        ]


class Newsletter(models.Model):
    """Модель «Рассылка»:"""

    STATUS_CHOICES = [
        ("завершена", "завершена"),
        ("создана", "создана"),
        ("запущена", "запущена"),
    ]

    sent_date = models.DateTimeField(auto_now_add=True)
    end_of_sending = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="создана")
    message = models.OneToOneField(Message, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(MailingRecipient, verbose_name="Получатели")
    owner = models.ForeignKey(
        CustomsUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return f"Рассылка с {self.recipients.count()} получателями"

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"
        ordering = ["status", "sent_date", "end_of_sending"]
        permissions = [
            ("can_view_all_mailings", "can view all mailings"),
            ("can_disable_mailings", "can disable mailings"),
        ]

    def block_mailing(self):
        self.is_blocked = True
        self.save()
        logging.info(f"Рассылка {self.pk} заблокирована пользователем {self.owner}")

    def unblock_mailing(self):
        self.is_blocked = False
        self.save()
        logging.info(f"Рассылка {self.pk} разблокирована пользователем {self.owner}")


class MailingAttempt(models.Model):
    """Модель «Попытка рассылки»"""

    STATUS_CHOICES = [("успешно", "успешно"), ("не успешно", "не успешно")]

    date_and_time_of_attempt = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    mail_server_response = models.TextField(blank=True)  # Разрешаем пустое значение
    newsletter = models.ForeignKey(
        Newsletter, on_delete=models.CASCADE, related_name="attempts"
    )
    recipients = models.ManyToManyField(MailingRecipient, blank=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = "Попытка"
        verbose_name_plural = "Попытки"
        ordering = ["status", "date_and_time_of_attempt"]
        permissions = [
            ("can_view_all_mailings_attempts", "can view all mailings attempts"),
        ]


class UserMailingStatistics(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # Используем settings.AUTH_USER_MODEL
    total_mailings = models.IntegerField(default=0)
    successful_mailings = models.IntegerField(default=0)
    failed_mailings = models.IntegerField(default=0)

    def update_statistics(self, success):
        self.total_mailings += 1
        if success:
            self.successful_mailings += 1
        else:
            self.failed_mailings += 1
        self.save()

newapp/forms.py
from django import forms
from django.forms import BooleanField

from newapp.models import Message, Newsletter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields["subject"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
                "placeholder": "Введите название продукта",
            }
        )  # Текст подсказки внутри поля

        self.fields["body_of_the_letter"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )


class NewsletterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Newsletter
        exclude = (
            "owner",
            "is_blocked",
            "success",
        )

newapp/templates/newapp/Newsletter_list.html
{% extends 'newapp/base.html'%}
{% block content %}

<main class="container">
  <div class="starter-template text-center py-5 px-3 mt-5">

    <h1>Список рассылок</h1>
    <table class="table mt-5">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Получатели</th>
          <th scope="col">Сообщение</th>
          <th scope="col">Статус</th>
          <th scope="col">Дата первой отправки</th>
          <th scope="col">Дата окончания отправки</th>
          <th scope="col">Владелец рассылки</th>
          <th scope="col">Разрешение</th>
          <th scope="col">Управление</th>
        </tr>
      </thead>
      {% for newapp in newapps %}
       {% if user == newapp.owner or user.is_staff or perms.newapp.can_view_all_mailings %}
      <tbody>
        <tr>
          <th scope="row">{{ newapp.id }}</th>
          <td>{{ newapp.recipients.all|join:", " }}</td>
          <td>{{ newapp.message }}</td>
          <td>{{ newapp.status }}</td>
          <td>{{ newapp.sent_date }}</td>
          <td>{{ newapp.end_of_sending }}</td>
          <td>{{ newapp.owner}}</td>
          <td>
            {% if mailing.is_blocked %}
                        Заблокировано
                    {% else %}
                        Разблокировано
                    {% endif %}</td>
          <td>
            {% if user == newapp.owner %}
            <a href="{% url 'newapp:newsletter_detail' newapp.id %}" class="btn btn-primary">посмотреть</a>
            <a href="{% url 'newapp:newsletter_update' newapp.id %}" class="btn btn-primary">редактировать</a>
            {% if user == newapp.owner or user.is_staff %}
            <!-- Добавлено обертывание в форму для отправки POST-запроса -->
            <form action="{% url 'newapp:send_newsletter' newapp.pk %}" method="POST" style="display:inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">отправить рассылку</button>
            </form>
            {% endif %}
            <a href="{% url 'newapp:newsletter_delete' newapp.id %}" class="btn btn-danger">удалить</a>
            {% else %}
            <a href="{% url 'newapp:newsletter_detail' newapp.id %}" class="btn btn-primary">посмотреть</a>
            {% endif %}
          </td>
        </tr>
      </tbody>
      {% endif %}
      {% endfor %}
    </table>
    <div class="d-flex justify-content-end mt-5">
      <a href="{% url 'newapp:newsletter_create' %}" class="btn btn-primary">Создать рассылку</a>
    </div>
  </div>
</main>
{% endblock %}

newapp/templates/newapp/base.html
<!doctype html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="index, follow"><link rel="canonical" href="https://bootstrap5.ru/examples/starter-template" />
<meta name="description" content="Ничего, кроме основ: скомпилированный CSS и JavaScript.">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors, Alexey Golyagin">
<meta name="docsearch:language" content="ru">
<meta name="docsearch:version" content="5.0">
<title>Рассылки</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootstrap5.ru/css/docs.css">
<!-- Favicons -->
<link rel="apple-touch-icon" href="https://bootstrap5.ru/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://bootstrap5.ru/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://bootstrap5.ru/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://bootstrap5.ru/img/favicons/manifest.json">
<link rel="mask-icon" href="https://bootstrap5.ru/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="https://bootstrap5.ru/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">
<!-- Facebook -->
<meta property="og:url" content="https://bootstrap5.ru/examples/starter-template">
<meta property="og:title" content="Бесплатный стартовый bootstrap 5 шаблон">
<meta property="og:description" content="Ничего, кроме основ: скомпилированный CSS и JavaScript.">
<meta property="og:type" content="website">
<meta property="og:image" content="https://bootstrap5.ru/img/examples/starter-template.png">
<meta property="og:image:type" content="image/jpg">
<meta property="og:image:width" content="1000">
<meta property="og:image:height" content="500">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    .custom-input {
        width: 500px;
    }
    .custom-margin {
        margin-top: 80px;
    }
    .clear-button-container {
          display: flex;
          justify-content: flex-end; /* Выравнивание по правому краю */
    }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"></head>
<body>
{% include 'newapp/includes/inc_menu.html'%}
{% block content %}
{% endblock %}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-179173139-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){ dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'UA-179173139-1');
</script>
{% include 'newapp/includes/inc_footer.html'%}
<!-- Yandex.Metrika counter --> <script type="text/javascript" > (function(m,e,t,r,i,k,a){ m[i]=m[i]||function(){ (m[i].a=m[i].a||[]).push(arguments) }; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(67718821, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/67718821" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

newapp/templates/newapp/home.html
{% extends 'newapp/base.html'%}
{% block content %}

<main class="container">

  <div class="starter-template text-center py-5 px-3 mt-5">


    <h1>Добро пожаловать на главную страницу</h1>
    <p class="lead">Используйте этот сервис для управления рассылками</p>
  </div>

    <h2>Статистика рассылок</h2>
    <ul>
        <li>Общее количество рассылок: {{ total_campaigns }}</li>
        <li>Активные рассылки: {{ active_campaigns }}</li>
        <li>Уникальные получатели: {{ unique_recipients }}</li>
    </ul>
</main>
{% endblock %}

newapp/templates/newapp/mailing_create.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h2 class="mb-2 custom-margin"> Добавить получателя</h2>
</div>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container mt-3 pt-3">
    <div class="mb-3">
      <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
      {{ form.email|add_class:"form-control custom-input" }}
      <div id="emailHelp" class="form-text">Мы никогда никому не передадим Вашу электронную почту.</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.full_name.id_for_label }}" class="form-label">ФИО</label>
      {{form.full_name|add_class:"form-control custom-input" }}
    </div>
    <div class="mb-3">
      <label for="{{.id_for_label }}" class="form-label">Комментарии</label>
      {{ form.comment|add_class:"form-control custom-input" }}
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'newapp:mailingrecipient_list' %}" class="btn btn-danger">Отмена</a>
  </div>
</form>
{% endblock %}

newapp/templates/newapp/mailing_delete.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Удалить получателя </h1>
        <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'newapp:home' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

newapp/templates/newapp/message_create.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Создать сообщение</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'newapp:message_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

newapp/templates/newapp/message_delete.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Удалить сообщение </h1>
        <p>Вы уверены, что хотите удалить сообщение?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'newapp:message_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

newapp/templates/newapp/message_detail.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
    <div class="card text-center custom-margin">
      <div class="card-header">
        {{ newapp.subject }}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ newapp.subject }}</h5>
        <p class="card-text">{{ newapp.body_of_the_letter}}</p>
        <a href="{% url 'newapp:message_list' %}" class="btn btn-primary">Вернуться</a>
      </div>
    </div>
{% endblock %}

newapp/templates/newapp/message_list.html
{% extends 'newapp/base.html'%}
{% block content %}

<main class="container">

  <div class="starter-template text-center py-5 px-3 mt-5">


    <h1>Список сообщений</h1>
    <table class="table mt-5">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Тема</th>
      <th scope="col">Сообщение</th>
      <th scope="col">Управление</th>
    </tr>
  </thead>
        {% for newapp in newapps %}
  <tbody>
    <tr>
      <th scope="row">{{ newapp.id }}</th>
      <td>{{ newapp.subject }}</td>
      <td>{{ newapp.body_of_the_letter}}</td>
        <td>
            <a href="{% url 'newapp:message_detail' newapp.id %}" class="btn btn-primary">прочитать</a>
            {% if user == newapp.owner %}
            <a href="{% url 'newapp:message_update' newapp.id %}" class="btn btn-primary">редактировать</a>
            <a href="{% url 'newapp:message_delete' newapp.id %}" class="btn btn-danger">удалить</a>
            {% endif %}
        </td>
    </tr>
  </tbody>
        {% endfor %}
</table>
<div class="d-flex justify-content-end mt-5">
    <a href="{% url 'newapp:message_create' %}" class="btn btn-primary">Создать сообщение</a>
</div>
  </div>
</main>
{% endblock %}

newapp/templates/newapp/newsletter_block.html
{% extends 'newapp/base.html' %}
{% block title %} Блокировка рассылки {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if mailing.is_blocked %}
            Разблокировать рассылку
        {% else %}
            Заблокировать рассылку
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if mailing.is_blocked %}разблокировать{% else %}
        заблокировать{% endif %} рассылку "{{ mailing.id }}"?</p>

    <form method="post">
        {% csrf_token %}
        <input type="checkbox" name="is_blocked" id="id_is_blocked" {% if mailing.is_blocked %}checked{% endif %}>
        <label for="id_is_blocked">
            {% if mailing.is_blocked %}
                Разблокировать рассылку
            {% else %}
                Заблокировать рассылку
            {% endif %}
        </label>
        <button type="submit" class="btn btn-primary">
            {% if mailing.is_blocked %}
                Разблокировать
            {% else %}
                Заблокировать
            {% endif %}
        </button>
        <a href="{% url 'newapp:newsletter_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

newapp/templates/newapp/newsletter_create.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Создать рассылку</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'newapp:newsletter_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

newapp/templates/newapp/newsletter_delete.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Удалить получателя </h1>
        <p>Вы уверены, что хотите удалить "{{ object.message }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'newapp:newsletter_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

newapp/templates/newapp/newsletter_detail.html
{% extends 'newapp/base.html'%}
{% load my_tags %}
{% block content %}
    <div class="card text-center custom-margin">
      <div class="card-header">
        {{ newapp.message }}
      </div>
      <div class="card-body">
        <h5 class="card-title">Получатели:{{ newapp.recipients.all|join:", " }}</h5>
        <p class="card-text">Статус:{{ newapp.status}}</p>
          <p class="card-text">Дата первой отправки:{{ newapp.sent_date}}</p>
          <p class="card-text">Дата окончания отправки: {{ newapp.end_of_sending}}</p>
        <a href="{% url 'newapp:newsletter_list' %}" class="btn btn-primary">Вернуться</a>
        {% if perms.spam.can_disable_mailings or user.is_staff %}
                    {% if mailing.is_blocked %}
        <a href="{% url 'newapp:newsletter_block' newapp.id %}" class="btn btn-danger">Разблокировать рассылку</a>
        {% else %}
        <a href="{% url 'newapp:newsletter_block' newapp.id %}" class="btn btn-danger">Заблокировать рассылку</a>
        {% endif %}
        {% endif %}
      </div>
    </div>
{% endblock %}

newapp/templates/newapp/user_statistics.html
{% extends "newapp/base.html" %}
{% load my_tags %}
{% block content %}
<div class="container custom-margin">
    <h2>Статистика рассылок для {{ user_stats.user.username }}</h2>
    <ul class="list-unstyled mt-4">
        <li>Всего рассылок: {{ user_stats.total_mailings }}</li>
        <li>Успешные рассылки: {{ user_stats.successful_mailings }}</li>
        <li>Неуспешные рассылки: {{ user_stats.failed_mailings }}</li>
    </ul>
    <a href="{% url 'newapp:home' %}">Назад на главную страницу</a>
</div>
<div class="container custom-margin">
    <h1>Детали пользователя: {{ user.username }}</h1>
    <div class="user-details">
        <img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
             style="max-width: 150px; max-height: 150px; width: auto; height: auto;">

        <ul>
            <li><strong>Email:</strong> {{ user.email }}</li>
            <li><strong>Имя:</strong> {{ user.first_name }}</li>
            <li><strong>Номер телефона:</strong> {{ user.phone_number }}</li>
            <li><strong>Страна:</strong> {{ user.country }}</li>
        </ul>
        <div class="card-body">
            <a class="btn btn-primary" href="{% url 'users:change_password' %}">Изменить пароль</a>
        </div>
    </div>
</div>
{% endblock %}