config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newapp.urls", namespace="newapp")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (BlockUserView, ChangePasswordView, PasswordResetView,
                    RegisterView, UserDetailView, UserListView,
                    email_verification)

app_name = "users"


urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="newapp:home"), name="logout"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_block/<int:user_id>", BlockUserView.as_view(), name="user_block"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("profile/<int:pk>", UserDetailView.as_view(), name="user_profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomsUser(AbstractUser):
    username = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    avatar = models.ImageField(upload_to="photo/avatars/", blank=True, null=True)

    token = models.CharField(
        max_length=100, verbose_name="Token", blank=True, null=True
    )
    country = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name="Страна",
        help_text="Укажите страну",
    )
    is_blocked = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "username",
    ]

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ["email"]
        permissions = [
            ("can_manage_users", "can manage users"),
            ("can_block_users", "can block users"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from newapp.forms import StyleFormMixin

from .models import CustomsUser


class CustomUserCreationForm(StyleFormMixin, UserCreationForm):
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Необязательное поле. Введите номер телефона",
    )
    username = forms.CharField(max_length=50, required=True)

    class Meta:
        model = CustomsUser
        fields = (
            "email",
            "avatar",
            "first_name",
            "username",
            "phone_number",
            "country",
        )
        exclude = (
            "is_blocked",
            "last_login",
            "is_superuser",
            "is_staff",
            "groups",
            "user_permissions",
            "date_joined",
            "is_active",
            "token",
        )

    def clean_avatar(self):
        avatar = self.cleaned_data.get("avatar")

        if avatar is None:
            return None

        if avatar.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Размер файла не должен превышать 5MB.")

        if not avatar.name.endswith((".jpg", ".jpeg", ".png")):
            raise forms.ValidationError(
                "Формат файла не соответствует требованиям. Допустимые форматы: *.jpg, *.jpeg, *.png"
            )

        return avatar

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен состоять только из цифр")
        return phone_number

users/views.py
import secrets
import string

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from config.settings import EMAIL_HOST_USER

from .forms import CustomUserCreationForm
from .models import CustomsUser


class RegisterView(CreateView):
    template_name = "users/register.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("newapp:home")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет, перейдите по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(CustomsUser, token=token)
    user.is_active = True
    user.save()
    return HttpResponse("подтвержден")


class UserListView(ListView):
    model = CustomsUser
    template_name = "users/user_lists.html"
    context_object_name = "users_list"

    def get_queryset(self):
        return CustomsUser.objects.all()


class UserDetailView(DetailView):
    model = CustomsUser
    template_name = "users/user_profile.html"
    context_object_name = "user_profile"


class BlockUserView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(CustomsUser, id=user_id)
        return render(request, "users/user_block.html", {"user": user})

    def post(self, request, user_id):
        user = get_object_or_404(CustomsUser, id=user_id)

        if not request.user.has_perm("users.can_block_users"):
            return HttpResponseForbidden("У вас нет прав для блокировки рассылки.")

        is_blocked = request.POST.get("is_blocked")
        user.is_blocked = is_blocked == "on"
        user.save()
        return redirect("users:user_list")


def generate_random_password(length: int = 12) -> str:
    """Генерирует случайный пароль заданной длины."""
    # Увеличена длина пароля до 12 символов для большей безопасности.
    alphabet = string.ascii_letters + string.digits + string.punctuation
    return "".join(secrets.choice(alphabet) for _ in range(length))


class PasswordResetView(View):
    def get(self, request):
        return render(request, "users/password_reset.html")

    def post(self, request):
        email = request.POST.get("email")
        try:
            user = CustomsUser.objects.get(email=email)
            new_password = generate_random_password()
            # 12 символов, включая пунктуацию
            user.password = make_password(new_password)
            user.save()
            send_mail(
                subject="Ваш новый пароль",
                message=f"Здравствуйте!\nВаш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            messages.success(request, "Новый пароль отправлен на ваш email.")
            return redirect("users:login")
        except CustomsUser.DoesNotExist:
            messages.error(request, "Пользователь с таким email не найден.")
            return render(request, "users/password_reset.html")


class ChangePasswordView(LoginRequiredMixin, View):
    def get(self, request):
        form = PasswordChangeForm(user=request.user)
        return render(request, "users/change_password.html", {"form": form})

    def post(self, request):
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            send_mail(
                subject="Ваш пароль был изменен",
                message=f"Здравствуйте, {user.username}!\n\nВаш пароль был успешно изменен.",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )

            messages.success(request, "Ваш пароль был успешно изменен!")
            return redirect("users:change_password")

        messages.error(request, "Пожалуйста, исправьте ошибки в форме.")
        return render(request, "users/change_password.html", {"form": form})

users/templates/users/change_password.html
{% extends 'newapp/home.html' %}
{% block title %} Изменение пароля пользователя {% endblock %}
{% block content %}
    {% if messages %}
    {% for message in messages %}
    <div class="container custom-margin">
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <h2>Изменить пароль</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="p-2 btn btn-outline-success"  type="submit">Изменить пароль</button>
    </form>
    <a class="p-2 btn btn-outline-primary"  href="{% url 'users:user_profile' user.id %}">Назад к профилю</a>
   </div>
{% endblock %}

users/templates/users/login.html
{% extends 'newapp/home.html' %}
{% block content %}
<div class="container mt-5 d-flex justify-content-center">
    <div class="col-md-6">
        <h1 class="mb-4 custom-margin text-center">Вход на сайт</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary w-100">Войти</button>
        </form>
        <div class="text-center mt-3">
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">Забыли пароль?</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'newapp/home.html' %}
{% block title %} Восстановление пароля {% endblock %}
{% block content %}
<div class="container custom-margin">
    <h1>Восстановление пароля</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Восстановить пароль</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'newapp/home.html'%}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4 custom-margin">Регистрация</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Регистрация</button>
        </form>
</div>
{% endblock %}

users/templates/users/user_block.html
{% extends 'newapp/home.html' %}
{% block title %} Блокировка пользователя {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if user.is_blocked %}
            Разблокировать пользователя
        {% else %}
            Заблокировать пользователя
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if user.is_blocked %}разблокировать{% else %}заблокировать{% endif %} пользователя "{{ user.email }}"?</p>

    <form method="post">
        {% csrf_token %}
        <input type="checkbox" name="is_blocked" id="id_is_blocked" {% if user.is_blocked %}checked{% endif %}>
        <label for="id_is_blocked">
            {% if user.is_blocked %}
                Разблокировать пользователя
            {% else %}
                Заблокировать пользователя
            {% endif %}
        </label>
        <button type="submit" class="btn btn-primary">
            {% if user.is_blocked %}
                Разблокировать
            {% else %}
                Заблокировать
            {% endif %}
        </button>
        <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

users/templates/users/user_lists.html
{% extends 'newapp/home.html' %}
{% load my_tags %}
{% block title %}Получатель рассылки{% endblock %}
{% block content %}
<h2>Список пользователей</h2>
<table class="table custom-margin">
    <thead>
        <tr>
            <th>Аватар</th>
            <th>Ф. И. О.</th>
            <th>Nikcname</th>
            <th>Телефон</th>
            <th>Email</th>
            <th>Страна</th>
            <th>Статус</th>
            <th>Управление</th>

        </tr>
    </thead>
    <tbody>
        {% for user in users_list %}
            {% if perms.users.can_manage_users and not user.is_superuser %}
            <tr>
                <td><img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
                         style="max-width: 150px; max-height: 150px; width: auto; height: auto;"></td>
                <td>{{ user.first_name }} {{user.last_name}}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.phone_number }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.country }}</td>
                <td>
                    {% if user.is_blocked %}
                        Заблокировано
                    {% else %}
                        Разблокировано
                    {% endif %}
                </td>
                {% if perms.users.can_block_users or user.is_staff %}

                {% if user.is_blocked %}
                    <td>
                        <a href="{% url 'users:user_block' user.id %}">Разблокировать пользователя</a>
                        <a href="{% url 'users:user_profile' user.id %}">Посмотреть</a>
                    </td>
                {% else %}
                    <td>
                        <a href="{% url 'users:user_block' user.id %}">Заблокировать пользователя</a>
                        <a href="{% url 'users:user_profile' user.id %}">Посмотреть</a>
                    </td>
                {% endif %}
                {% endif %}
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'newapp/home.html' %}
{% load my_tags %}
{% block content %}
<h1>Детали пользователя: {{ user_profile.username }}</h1>

<div class="user-details">
    <img src="{{ user_profile.avatar.url }}" class="card-img-top" alt="avatar"
         style="max-width: 150px; max-height: 150px; width: auto; height: auto;">

    <ul>
        <li><strong>Email:</strong> {{ user_profile.email }}</li>
        <li><strong>Имя:</strong> {{ user_profile.first_name }}</li>
        <li><strong>Номер телефона:</strong> {{ user_profile.phone_number }}</li>
        <li><strong>Страна:</strong> {{ user_profile.country }}</li>
    </ul>
    <div class="card">
        <div class="card-body">
            <a class="btn btn-primary" href="{% url 'users:change_password' %}">Изменить пароль</a>
        </div>
    </div>
</div>

{% endblock %}